### ISSUE TITLE
Infinite loop possible when housekeeeping collection fails

### ISSUE THREAD

**Issue by Taylorr82** [AlbertaSat/ex2_obc_software#126]
This line should use a semaphore to allow timeouts. 

Also, DFGM_IS_STUBBED should be added around the DFGM collection so no attempt is made when DFGM is not enabled.

https://github.com/AlbertaSat/ex2_obc_software/blob/aa974c1400a1a691484c1ff1e64bb09d9e36fea5/ex2_hal/dfgm/equipment_handler/source/dfgm_handler.c#L535

**Comment by DanielSacro** [comment]
By "DFGM_IS_STUBBED should be added around the DFGM collection", do you mean in the dfgm_rx_task around the code that processes/saves data (around lines 365-418) or do you mean in the function DFGM_get_HK() around the code that updates HK (around lines 531-553)?

**Comment by DanielSacro** [comment]
@Taylorr82

**Comment by tganley** [comment]
Checks for DFGM_IS_STUBBED already exist in the HAL so I don't think it's necessary here. But Robert's right that if something goes wrong in the rx task and collecting_hk never gets changed back to 0, this will loop indefinitely. There should be a timeout so that in this scenario an error is returned

**Comment by tganley** [comment]
So just make collecting_hk a semaphore and then you can set a reasonable timeout

**Comment by Taylorr82** [comment]
closed by #251
